import { afterAll, beforeAll, expect, test } from "vitest";
import { asc, eq } from "drizzle-orm";
import { type Database, attachments, messages } from "@sidekick/db";
import { createTestDb } from "@sidekick/db/testing";
import {
  attachmentExpansionTokens,
  decodeStreamMeta,
  encodeStreamMeta,
  estimateTokens,
  parseSuggestedReplies,
  STREAM_META_PREFIX,
} from "@sidekick/shared";
import { registerDevice, sendChatTurn } from "@sidekick/server";
import { createConversation, generateModel, makeCaller, testStorage, textModel } from "./helpers";

let db: Database;
let close: () => Promise<void>;

beforeAll(async () => {
  ({ db, close } = await createTestDb());
});

afterAll(async () => {
  await close();
});

test("parseSuggestedReplies bounds and sanitizes model output", () => {
  expect(parseSuggestedReplies('["yes!", "not today"]')).toEqual(["yes!", "not today"]);
  expect(parseSuggestedReplies('here you go: ["a","b","c","d"]')).toEqual(["a", "b", "c"]);
  expect(parseSuggestedReplies('["ok", 42, "", "  "]')).toEqual(["ok"]);
  expect(parseSuggestedReplies("no json at all")).toEqual([]);
  expect(parseSuggestedReplies("[not valid")).toEqual([]);
  expect(parseSuggestedReplies(`["${"x".repeat(80)}"]`)).toEqual([]);
});

test("the stream-meta frame round-trips", () => {
  const frame = encodeStreamMeta({ replies: ["sounds good"], beat: "reminder" });
  expect(frame.startsWith(STREAM_META_PREFIX)).toBe(true);
  const payload = frame.slice(STREAM_META_PREFIX.length, -1);
  expect(decodeStreamMeta(payload)).toEqual({ replies: ["sounds good"], beat: "reminder" });
  expect(decodeStreamMeta("not json")).toBeNull();
  expect(decodeStreamMeta('{"beat":"x"}')).toBeNull();
});

test("a plain turn carries suggested replies generated by the reply model", async () => {
  const { userId } = await registerDevice(db, { deviceId: "replies-basic" });
  const conversationId = await createConversation(db, userId);
  const caller = makeCaller(db, textModel("proud of u!"), userId, {
    captionModel: generateModel('["thanks!!", "more tomorrow"]'),
  });

  const outcome = await caller.chat.send({ conversationId, text: "i actually made it to the gym" });
  expect(outcome.suggestedReplies).toEqual(["thanks!!", "more tomorrow"]);
});

test("the suggested_replies flag disables the post-hoc call", async () => {
  const { userId } = await registerDevice(db, { deviceId: "replies-flag" });
  const conversationId = await createConversation(db, userId);

  const outcome = await sendChatTurn(
    {
      db,
      model: textModel("hey!"),
      flags: { suggested_replies: false },
      userId,
      storage: testStorage(),
      replyModel: generateModel('["should not appear"]'),
    },
    { conversationId, text: "hi" },
  );
  expect(outcome.suggestedReplies).toEqual([]);
});

test("a failing reply model yields no chips, never a failed turn", async () => {
  const { userId } = await registerDevice(db, { deviceId: "replies-error" });
  const conversationId = await createConversation(db, userId);
  const caller = makeCaller(db, textModel("all good"), userId, {
    captionModel: generateModel("i am not json"),
  });
  const outcome = await caller.chat.send({ conversationId, text: "hello" });
  expect(outcome.suggestedReplies).toEqual([]);
});

test("attachment expansion counts into the user message's tokenEstimate", async () => {
  const { userId } = await registerDevice(db, { deviceId: "replies-tokens" });
  const conversationId = await createConversation(db, userId);
  const caller = makeCaller(db, textModel("got the file"), userId, { storage: testStorage() });

  const created = await caller.chat.createUploadUrl({
    kind: "file",
    mime: "text/plain",
    bytes: 4096,
    filename: "notes.txt",
  });
  const extractedText = "meeting notes ".repeat(400);
  await db
    .update(attachments)
    .set({ status: "ready", extractedText, caption: "meeting notes" })
    .where(eq(attachments.id, created.attachmentId));

  const text = "summarize this for me";
  await caller.chat.send({ conversationId, text, attachmentIds: [created.attachmentId] });

  const rows = await db
    .select()
    .from(messages)
    .where(eq(messages.conversationId, conversationId))
    .orderBy(asc(messages.id));
  const userRow = rows.find((r) => r.role === "user");
  const attachmentRow = await db
    .select({
      kind: attachments.kind,
      storageKey: attachments.storageKey,
      caption: attachments.caption,
      transcript: attachments.transcript,
      extractedText: attachments.extractedText,
    })
    .from(attachments)
    .where(eq(attachments.id, created.attachmentId));

  const expected = estimateTokens(text) + attachmentExpansionTokens(attachmentRow[0]!);
  expect(userRow?.tokenEstimate).toBe(expected);
  expect(userRow?.tokenEstimate ?? 0).toBeGreaterThan(estimateTokens(text) + 1000);
});
