// GENERATED by scripts/sync-cosmetics.mjs — do not edit by hand.
//
// Metro requires bundled assets to be static require() calls, so the catalog
// ships as this module rather than a fetched JSON file. Structure mirrors the
// canonical assets/cosmetics/manifest.json — model/tex are Metro
// module refs instead of URL strings, and variant textures are PNG (converted
// from the canonical .webp; expo-gl can't decode .webp). The phone slot reuses
// the already-bundled stripped mascot phone GLB.

export type Variant = {
  id: string;
  name: string;
  tex?: number; // require() module ref of the albedo PNG
  color?: string;
  roughness?: number;
  metalness?: number;
  emissive?: string;
};
export type SlotDef = {
  model: number; // require() module ref of the (stripped) slot GLB
  attach: string; // "skinned" | "bone:<BoneName>"
  defaultColor?: string;
  scale?: number; // rigid-attach only: multiply the authored local scale
  offset?: [number, number, number]; // rigid-attach only: nudge in bone-local space
  rotate?: [number, number, number]; // rigid-attach only: euler degrees, bone-local, pivots on the bone origin
  variants: Variant[];
};
export type Manifest = Record<string, SlotDef>;

export const MANIFEST: Manifest = {
  shirt: {
    model: require('../../assets/cosmetics/shirt/base-v1.stripped.glb'),
    attach: 'skinned',
    variants: [
      { id: 'sky', name: "Sky Blue", tex: require('../../assets/cosmetics/shirt/sky.png') },
      { id: 'coral', name: "Coral", tex: require('../../assets/cosmetics/shirt/coral.png'), roughness: 0.55 },
      { id: 'dots', name: "Polka", tex: require('../../assets/cosmetics/shirt/dots.png') },
    ],
  },
  pants: {
    model: require('../../assets/cosmetics/pants/base-v1.stripped.glb'),
    attach: 'skinned',
    variants: [
      { id: 'denim', name: "Denim", tex: require('../../assets/cosmetics/pants/denim.png') },
      { id: 'khaki', name: "Khaki", tex: require('../../assets/cosmetics/pants/khaki.png'), roughness: 0.85 },
    ],
  },
  hat: {
    model: require('../../assets/cosmetics/hat/base-v1.stripped.glb'),
    attach: 'bone:Head',
    scale: 0.76,
    offset: [0, 0.028, 0],
    variants: [
      { id: 'khaki', name: "Khaki", tex: require('../../assets/cosmetics/hat/khaki.png') },
      { id: 'forest', name: "Forest", tex: require('../../assets/cosmetics/hat/forest.png') },
      { id: 'berry', name: "Berry", tex: require('../../assets/cosmetics/hat/berry.png') },
    ],
  },
  shoes: {
    model: require('../../assets/cosmetics/shoes/base-v1.stripped.glb'),
    attach: 'bone:Calf',
    variants: [
      { id: 'red', name: "Red", tex: require('../../assets/cosmetics/shoes/red.png') },
      { id: 'white', name: "White", tex: require('../../assets/cosmetics/shoes/white.png'), roughness: 0.5 },
    ],
  },
  phone: {
    model: require('../../assets/models/phone.stripped.glb'),
    attach: 'bone:R_Hand',
    scale: 1.7,
    offset: [0, 0, 0],
    variants: [
      { id: 'default', name: "Phone" },
    ],
  },
  hoodie: {
    model: require('../../assets/cosmetics/shirt/hoodie-v1.stripped.glb'),
    attach: 'skinned',
    variants: [
      { id: 'heather', name: "Heather", tex: require('../../assets/cosmetics/shirt/heather.png'), roughness: 0.85 },
      { id: 'navy', name: "Navy", tex: require('../../assets/cosmetics/shirt/navy-h.png'), roughness: 0.85 },
      { id: 'crimson', name: "Crimson", tex: require('../../assets/cosmetics/shirt/crimson.png'), roughness: 0.85 },
    ],
  },
  shorts: {
    model: require('../../assets/cosmetics/pants/shorts-v1.stripped.glb'),
    attach: 'skinned',
    variants: [
      { id: 'navy', name: "Gym Navy", tex: require('../../assets/cosmetics/pants/gym-navy.png') },
      { id: 'red', name: "Gym Red", tex: require('../../assets/cosmetics/pants/gym-red.png') },
      { id: 'black', name: "Gym Black", tex: require('../../assets/cosmetics/pants/gym-black.png') },
    ],
  },
  beanie: {
    model: require('../../assets/cosmetics/hat/beanie-v1.stripped.glb'),
    attach: 'bone:Head',
    scale: 0.76,
    offset: [0, 0.028, 0],
    variants: [
      { id: 'charcoal', name: "Charcoal", tex: require('../../assets/cosmetics/hat/charcoal.png'), roughness: 0.9 },
      { id: 'tangerine', name: "Tangerine", tex: require('../../assets/cosmetics/hat/tangerine.png'), roughness: 0.9 },
      { id: 'teal', name: "Teal", tex: require('../../assets/cosmetics/hat/teal.png'), roughness: 0.9 },
    ],
  },
  bucket: {
    model: require('../../assets/cosmetics/hat/bucket-v1.stripped.glb'),
    attach: 'bone:Head',
    scale: 0.76,
    offset: [0, 0.028, 0],
    variants: [
      { id: 'sand', name: "Sand", tex: require('../../assets/cosmetics/hat/sand.png') },
      { id: 'night', name: "Night", tex: require('../../assets/cosmetics/hat/night.png') },
    ],
  },
  wizard: {
    model: require('../../assets/cosmetics/hat/wizard-v1.stripped.glb'),
    attach: 'bone:Head',
    scale: 0.76,
    offset: [0, 0.028, 0],
    variants: [
      { id: 'purple', name: "Arcane", tex: require('../../assets/cosmetics/hat/wiz-purple.png') },
      { id: 'night', name: "Starry Night", tex: require('../../assets/cosmetics/hat/wiz-night.png') },
    ],
  },
  crown: {
    model: require('../../assets/cosmetics/hat/crown-v1.stripped.glb'),
    attach: 'bone:Head',
    scale: 0.76,
    offset: [0, 0.028, 0],
    variants: [
      { id: 'gold', name: "Gold", tex: require('../../assets/cosmetics/hat/gold.png'), roughness: 0.35 },
      { id: 'silver', name: "Silver", tex: require('../../assets/cosmetics/hat/silver.png'), roughness: 0.3 },
    ],
  },
  sneakers: {
    model: require('../../assets/cosmetics/shoes/sneakers-v1.stripped.glb'),
    attach: 'bone:Calf',
    variants: [
      { id: 'white', name: "Classic White", tex: require('../../assets/cosmetics/shoes/snk-white.png'), roughness: 0.55 },
      { id: 'black', name: "Black", tex: require('../../assets/cosmetics/shoes/snk-black.png'), roughness: 0.55 },
      { id: 'red', name: "Red", tex: require('../../assets/cosmetics/shoes/snk-red.png'), roughness: 0.55 },
    ],
  },
  boots: {
    model: require('../../assets/cosmetics/shoes/boots-v1.stripped.glb'),
    attach: 'bone:Calf',
    variants: [
      { id: 'brown', name: "Leather", tex: require('../../assets/cosmetics/shoes/boot-brown.png'), roughness: 0.75 },
      { id: 'black', name: "Black", tex: require('../../assets/cosmetics/shoes/boot-black.png'), roughness: 0.75 },
    ],
  },
  glasses: {
    model: require('../../assets/cosmetics/glasses/base-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'black', name: "Black", tex: require('../../assets/cosmetics/glasses/black.png'), roughness: 0.25 },
      { id: 'white', name: "White", tex: require('../../assets/cosmetics/glasses/white.png'), roughness: 0.25 },
      { id: 'pink', name: "Pink", tex: require('../../assets/cosmetics/glasses/pink.png'), roughness: 0.25 },
    ],
  },
  backpack: {
    model: require('../../assets/cosmetics/back/backpack-v1.stripped.glb'),
    attach: 'bone:Spine01',
    variants: [
      { id: 'red', name: "Red", tex: require('../../assets/cosmetics/back/bp-red.png') },
      { id: 'sky', name: "Sky", tex: require('../../assets/cosmetics/back/bp-sky.png') },
      { id: 'forest', name: "Forest", tex: require('../../assets/cosmetics/back/bp-forest.png') },
    ],
  },
  headphones: {
    model: require('../../assets/cosmetics/hat/headphones-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'charcoal', name: "Charcoal", color: '#34353b', roughness: 0.5 },
      { id: 'white', name: "White", color: '#eceff2', roughness: 0.5 },
      { id: 'pink', name: "Pink", color: '#e88bb4', roughness: 0.5 },
    ],
  },
  earmuffs: {
    model: require('../../assets/cosmetics/hat/earmuffs-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'white', name: "Snow", color: '#f1f2f4', roughness: 0.85 },
      { id: 'pink', name: "Pink", color: '#f2b8cd', roughness: 0.85 },
      { id: 'lavender', name: "Lavender", color: '#b9a8e6', roughness: 0.85 },
    ],
  },
  sweatband: {
    model: require('../../assets/cosmetics/hat/sweatband-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'red', name: "Red", color: '#e05548', roughness: 0.9 },
      { id: 'teal', name: "Teal", color: '#2f9e8f', roughness: 0.9 },
      { id: 'charcoal', name: "Charcoal", color: '#3a3f47', roughness: 0.9 },
    ],
  },
  laurel: {
    model: require('../../assets/cosmetics/hat/laurel-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'gold', name: "Gold", color: '#d4af37', roughness: 0.3, metalness: 0.45 },
      { id: 'green', name: "Victory Green", color: '#5a9e4d', roughness: 0.7 },
    ],
  },
  propeller: {
    model: require('../../assets/cosmetics/hat/propeller-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'red', name: "Cherry", color: '#e0554a', roughness: 0.5 },
      { id: 'blue', name: "Sky", color: '#4a8fe0', roughness: 0.5 },
    ],
  },
  catbeanie: {
    model: require('../../assets/cosmetics/hat/catbeanie-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'black', name: "Black Cat", color: '#26252b', roughness: 0.9 },
      { id: 'pink', name: "Pink Cat", color: '#f0a3c0', roughness: 0.9 },
      { id: 'grey', name: "Grey Cat", color: '#9aa0a8', roughness: 0.9 },
    ],
  },
  cowboy: {
    model: require('../../assets/cosmetics/hat/cowboy-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'tan', name: "Tan", color: '#c89a5e', roughness: 0.8 },
      { id: 'brown', name: "Brown", color: '#7a5a3c', roughness: 0.8 },
      { id: 'black', name: "Black", color: '#33343a', roughness: 0.8 },
    ],
  },
  stars: {
    model: require('../../assets/cosmetics/glasses/stars-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'gold', name: "Gold", color: '#ddab3d', roughness: 0.35, metalness: 0.15 },
      { id: 'pink', name: "Pink", color: '#ee9ab5', roughness: 0.35 },
      { id: 'blue', name: "Blue", color: '#7db3e8', roughness: 0.35 },
    ],
  },
  goggles: {
    model: require('../../assets/cosmetics/glasses/goggles-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'blue', name: "Alpine", color: '#4a73e0', roughness: 0.3 },
      { id: 'orange', name: "Sunset", color: '#eb7326', roughness: 0.3 },
      { id: 'teal', name: "Glacier", color: '#2f9e8f', roughness: 0.3 },
    ],
  },
  snorkel: {
    model: require('../../assets/cosmetics/glasses/snorkel-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'aqua', name: "Aqua", color: '#35a0a8', roughness: 0.35 },
      { id: 'pink', name: "Reef Pink", color: '#ee7fae', roughness: 0.35 },
    ],
  },
  earring: {
    model: require('../../assets/cosmetics/ear/earring-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'gold', name: "Gold", color: '#ddab3d', roughness: 0.25, metalness: 0.85 },
      { id: 'silver', name: "Silver", color: '#c9ced6', roughness: 0.25, metalness: 0.85 },
    ],
  },
  flower: {
    model: require('../../assets/cosmetics/ear/flower-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'white', name: "Daisy", color: '#f3f0e8', roughness: 0.6 },
      { id: 'pink', name: "Blossom", color: '#f0a3c0', roughness: 0.6 },
      { id: 'blue', name: "Forget-me-not", color: '#8fb7e8', roughness: 0.6 },
    ],
  },
  earbow: {
    model: require('../../assets/cosmetics/ear/earbow-v1.stripped.glb'),
    attach: 'bone:Head',
    variants: [
      { id: 'red', name: "Cherry", color: '#d94a5b', roughness: 0.6 },
      { id: 'pink', name: "Pink", color: '#ee9ab5', roughness: 0.6 },
      { id: 'black', name: "Black", color: '#33343a', roughness: 0.6 },
    ],
  },
  scarf: {
    model: require('../../assets/cosmetics/neck/scarf-v1.stripped.glb'),
    attach: 'bone:Spine01',
    variants: [
      { id: 'red', name: "Cranberry", color: '#b73a3f', roughness: 0.95 },
      { id: 'cream', name: "Cream", color: '#efe6d6', roughness: 0.95 },
      { id: 'forest', name: "Forest", color: '#3f7a4d', roughness: 0.95 },
    ],
  },
};
