// GENERATED by packages/expo/scripts/sync-cosmetics.mjs — do not edit by hand,
// but DO keep it checked in: this is the canonical cosmetics catalog data that
// the server and the app both build the shop product list from. Slot ids plus
// variant ids/display names only — no texture refs or asset paths (those live
// in each app's own manifest). Derived from the canonical
// packages/web/public/cosmetics/manifest.json; re-run the sync script whenever
// the art catalog changes. Variant order is load-bearing (prices step by index).

export type CatalogSlotId =
  | 'backpack'
  | 'beanie'
  | 'boots'
  | 'bucket'
  | 'catbeanie'
  | 'cowboy'
  | 'crown'
  | 'earbow'
  | 'earmuffs'
  | 'earring'
  | 'flower'
  | 'glasses'
  | 'goggles'
  | 'hat'
  | 'headphones'
  | 'hoodie'
  | 'laurel'
  | 'pants'
  | 'propeller'
  | 'scarf'
  | 'shirt'
  | 'shoes'
  | 'shorts'
  | 'sneakers'
  | 'snorkel'
  | 'stars'
  | 'sweatband'
  | 'wizard';

export type CatalogVariant = { id: string; name: string };

export const CATALOG_VARIANTS: Record<CatalogSlotId, readonly CatalogVariant[]> = {
  backpack: [
    { id: 'red', name: "Red" },
    { id: 'sky', name: "Sky" },
    { id: 'forest', name: "Forest" },
  ],
  beanie: [
    { id: 'charcoal', name: "Charcoal" },
    { id: 'tangerine', name: "Tangerine" },
    { id: 'teal', name: "Teal" },
  ],
  boots: [
    { id: 'brown', name: "Leather" },
    { id: 'black', name: "Black" },
  ],
  bucket: [
    { id: 'sand', name: "Sand" },
    { id: 'night', name: "Night" },
  ],
  catbeanie: [
    { id: 'black', name: "Black Cat" },
    { id: 'pink', name: "Pink Cat" },
    { id: 'grey', name: "Grey Cat" },
  ],
  cowboy: [
    { id: 'tan', name: "Tan" },
    { id: 'brown', name: "Brown" },
    { id: 'black', name: "Black" },
  ],
  crown: [
    { id: 'gold', name: "Gold" },
    { id: 'silver', name: "Silver" },
  ],
  earbow: [
    { id: 'red', name: "Cherry" },
    { id: 'pink', name: "Pink" },
    { id: 'black', name: "Black" },
  ],
  earmuffs: [
    { id: 'white', name: "Snow" },
    { id: 'pink', name: "Pink" },
    { id: 'lavender', name: "Lavender" },
  ],
  earring: [
    { id: 'gold', name: "Gold" },
    { id: 'silver', name: "Silver" },
  ],
  flower: [
    { id: 'white', name: "Daisy" },
    { id: 'pink', name: "Blossom" },
    { id: 'blue', name: "Forget-me-not" },
  ],
  glasses: [
    { id: 'black', name: "Black" },
    { id: 'white', name: "White" },
    { id: 'pink', name: "Pink" },
  ],
  goggles: [
    { id: 'blue', name: "Alpine" },
    { id: 'orange', name: "Sunset" },
    { id: 'teal', name: "Glacier" },
  ],
  hat: [
    { id: 'khaki', name: "Khaki" },
    { id: 'forest', name: "Forest" },
    { id: 'berry', name: "Berry" },
  ],
  headphones: [
    { id: 'charcoal', name: "Charcoal" },
    { id: 'white', name: "White" },
    { id: 'pink', name: "Pink" },
  ],
  hoodie: [
    { id: 'heather', name: "Heather" },
    { id: 'navy', name: "Navy" },
    { id: 'crimson', name: "Crimson" },
  ],
  laurel: [
    { id: 'gold', name: "Gold" },
    { id: 'green', name: "Victory Green" },
  ],
  pants: [
    { id: 'denim', name: "Denim" },
    { id: 'khaki', name: "Khaki" },
  ],
  propeller: [
    { id: 'red', name: "Cherry" },
    { id: 'blue', name: "Sky" },
  ],
  scarf: [
    { id: 'red', name: "Cranberry" },
    { id: 'cream', name: "Cream" },
    { id: 'forest', name: "Forest" },
  ],
  shirt: [
    { id: 'sky', name: "Sky Blue" },
    { id: 'coral', name: "Coral" },
    { id: 'dots', name: "Polka" },
  ],
  shoes: [
    { id: 'red', name: "Red" },
    { id: 'white', name: "White" },
  ],
  shorts: [
    { id: 'navy', name: "Gym Navy" },
    { id: 'red', name: "Gym Red" },
    { id: 'black', name: "Gym Black" },
  ],
  sneakers: [
    { id: 'white', name: "Classic White" },
    { id: 'black', name: "Black" },
    { id: 'red', name: "Red" },
  ],
  snorkel: [
    { id: 'aqua', name: "Aqua" },
    { id: 'pink', name: "Reef Pink" },
  ],
  stars: [
    { id: 'gold', name: "Gold" },
    { id: 'pink', name: "Pink" },
    { id: 'blue', name: "Blue" },
  ],
  sweatband: [
    { id: 'red', name: "Red" },
    { id: 'teal', name: "Teal" },
    { id: 'charcoal', name: "Charcoal" },
  ],
  wizard: [
    { id: 'purple', name: "Arcane" },
    { id: 'night', name: "Starry Night" },
  ],
};
